### ISSUE TITLE
Migrations in backend run before database is done loading

### ISSUE THREAD

**Issue by jmai136** [SpadeBoard/Spadeboard#18]

**Comment by ZachHunt359** [comment]
I'm running into the same login issue again.

![image](https://github.com/user-attachments/assets/77d1ade7-6287-45a9-930c-debc23d650e7)


Here's the output (similar to before - it says the database is ready, but then the migrations have error):

> PS D:\Dev\SpadeBoard\Spadeboard> docker-compose up --build
> [+] Building 2.5s (25/25) FINISHED                                                                                                                 docker:desktop-linux 
>  => [backend internal] load build definition from Dockerfile                                                                                                       0.0s 
>  => => transferring dockerfile: 1.15kB                                                                                                                             0.0s 
>  => [backend internal] load metadata for docker.io/library/python:latest                                                                                           1.0s 
>  => [backend auth] library/python:pull token for registry-1.docker.io                                                                                              0.0s 
>  => [backend internal] load .dockerignore                                                                                                                          0.0s 
>  => => transferring context: 375B                                                                                                                                  0.0s 
>  => [backend 1/6] FROM docker.io/library/python:latest@sha256:e3d5b6f95ce66923b5e48a06ee5755abb097de96a8617c3f2f7d431d48e63d35                                     0.0s 
>  => [backend internal] load build context                                                                                                                          0.0s 
>  => => transferring context: 18.50kB                                                                                                                               0.0s 
>  => CACHED [backend 2/6] COPY ./backend/requirements.txt /app/backend/requirements.txt                                                                             0.0s 
>  => CACHED [backend 3/6] RUN python -m pip install -r /app/backend/requirements.txt                                                                                0.0s 
>  => CACHED [backend 4/6] WORKDIR /app/backend                                                                                                                      0.0s 
>  => CACHED [backend 5/6] COPY ./backend /app/backend                                                                                                               0.0s 
>  => CACHED [backend 6/6] RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app/backend                                               0.0s 
>  => [backend] exporting to image                                                                                                                                   0.0s 
>  => => exporting layers                                                                                                                                            0.0s 
>  => => writing image sha256:08854eb2961b17438bb037f30237d186eff3efa3e796d1a506018c026b53ea6a                                                                       0.0s 
>  => => naming to docker.io/library/spadeboard-backend                                                                                                              0.0s 
>  => [backend] resolving provenance for metadata file                                                                                                               0.0s 
>  => [frontend internal] load build definition from Dockerfile                                                                                                      0.0s 
>  => => transferring dockerfile: 549B                                                                                                                               0.0s 
>  => [frontend internal] load metadata for docker.io/library/node:latest                                                                                            0.9s 
>  => [frontend auth] library/node:pull token for registry-1.docker.io                                                                                               0.0s 
>  => [frontend internal] load .dockerignore                                                                                                                         0.0s 
>  => => transferring context: 375B                                                                                                                                  0.0s 
>  => [frontend 1/5] FROM docker.io/library/node:latest@sha256:54b7a9a6bb4ebfb623b5163581426b83f0ab39292e4df2c808ace95ab4cba94f                                      0.0s 
>  => [frontend internal] load build context                                                                                                                         0.1s 
>  => => transferring context: 1.08MB                                                                                                                                0.0s 
>  => CACHED [frontend 2/5] WORKDIR /app/frontend                                                                                                                    0.0s 
>  => CACHED [frontend 3/5] COPY ./frontend/package*.json ./                                                                                                         0.0s 
>  => CACHED [frontend 4/5] RUN npm install                                                                                                                          0.0s 
>  => CACHED [frontend 5/5] COPY ./frontend ./                                                                                                                       0.0s 
>  => [frontend] exporting to image                                                                                                                                  0.0s 
>  => => exporting layers                                                                                                                                            0.0s 
>  => => writing image sha256:ce4db4be6fa297394165363000232dad977e6d4991cecf6c63f967e1d576bcdb                                                                       0.0s 
>  => => naming to docker.io/library/spadeboard-frontend                                                                                                             0.0s 
>  => [frontend] resolving provenance for metadata file                                                                                                              0.0s 
> [+] Running 4/0
>  ✔ Container db        Created                                                                                                                                     0.0s 
>  ✔ Container pgadmin   Created                                                                                                                                     0.0s 
>  ✔ Container backend   Created                                                                                                                                     0.0s 
>  ✔ Container frontend  Created                                                                                                                                     0.0s 
> Attaching to backend, db, frontend, pgadmin
> db        | 
> db        | PostgreSQL Database directory appears to contain a database; Skipping initialization
> db        | 
> db        | 2024-08-26 22:35:05.884 UTC [1] LOG:  starting PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit 
> db        | 2024-08-26 22:35:05.885 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> db        | 2024-08-26 22:35:05.885 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> db        | 2024-08-26 22:35:05.889 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> db        | 2024-08-26 22:35:05.895 UTC [29] LOG:  database system was shut down at 2024-08-26 22:30:52 UTC
> db        | 2024-08-26 22:35:05.912 UTC [1] LOG:  database system is ready to accept connections
> backend   | /app/backend/entrypoint.sh: line 2: $'\r': command not found
> pgadmin   | postfix/postlog: starting the Postfix mail system
> frontend  | 
> frontend  | > frontend@0.0.0 dev
> frontend  | > vite
> frontend  | 
> frontend  | 
> frontend  |   VITE v5.3.2  ready in 266 ms
> frontend  | 
> frontend  |   ➜  Local:   http://localhost:3000/
> frontend  |   ➜  Network: http://172.19.0.3:3000/
> backend   | usage: manage.py makemigrations [-h] [--dry-run] [--merge] [--empty]
> backend   |                                 [--noinput] [-n NAME] [--no-header] [--check]
> backend   |                                 [--scriptable] [--update] [--version]
> backend   |                                 [-v {0,1,2,3}] [--settings SETTINGS]
> backend   |                                 [--pythonpath PYTHONPATH] [--traceback]
> backend   |                                 [--no-color] [--force-color] [--skip-checks]
> backend   |                                 [app_label ...]
> backend   | manage.py makemigrations: error: unrecognized arguments: --no-input
> backend   | usage: manage.py migrate [-h] [--noinput] [--database DATABASE] [--fake]
> backend   |                          [--fake-initial] [--plan] [--run-syncdb] [--check]
> backend   |                          [--prune] [--version] [-v {0,1,2,3}]
> backend   |                          [--settings SETTINGS] [--pythonpath PYTHONPATH]
> backend   |                          [--traceback] [--no-color] [--force-color]
> backend   |                          [--skip-checks]
> backend   |                          [app_label] [migration_name]
> backend   | manage.py migrate: error: unrecognized arguments: --no-input
> backend   | /app/backend/entrypoint.sh: line 6: $'\r': command not found
> backend   | Watching for file changes with StatReloader
> backend   | Performing system checks...
> backend   | 
> backend   | System check identified no issues (0 silenced).
> backend   | Exception in thread django-main-thread:
> backend   | Traceback (most recent call last):
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 187, in check_key
> backend   |     return self.graph.root_nodes(key[0])[0]
> backend   |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> backend   | IndexError: list index out of range
> backend   | 
> backend   | During handling of the above exception, another exception occurred:
> backend   | 
> backend   | Traceback (most recent call last):
> backend   |   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
> backend   |     self.run()
> backend   |   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
> backend   |     self._target(*self._args, **self._kwargs)
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
> backend   |     fn(*args, **kwargs)
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
> backend   |     self.check_migrations()
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 581, in check_migrations
> backend   |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
> backend   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
> backend   |     self.loader = MigrationLoader(self.connection)
> backend   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
> backend   |     self.build_graph()
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 250, in build_graph
> backend   |     self.add_external_dependencies(key, migration)
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
> backend   |     parent = self.check_key(parent, key[0])
> backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 194, in check_key
> backend   |     raise ValueError(
> backend   | ValueError: Dependency on app with no migrations: authentication
> pgadmin   | [2024-08-26 22:35:22 +0000] [1] [INFO] Starting gunicorn 22.0.0
> pgadmin   | [2024-08-26 22:35:22 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
> pgadmin   | [2024-08-26 22:35:22 +0000] [1] [INFO] Using worker: gthread
> pgadmin   | [2024-08-26 22:35:22 +0000] [83] [INFO] Booting worker with pid: 83
> 
> 
> v View in Docker Desktop   o View Config   w Enable Watch
