### ISSUE TITLE
Can't install React Reparenting

### ISSUE THREAD

**Issue by jmai136** [SpadeBoard/Spadeboard#23]
### Description
Can't install `react-reparenting` package

### To Reproduce
Cd to `frontend` and run `npm i react-reparenting`

### Error message
```npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: frontend@0.0.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"^18.3.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.8.5 || ^17.0.1" from react-reparenting@0.6.1
npm error node_modules/react-reparenting
npm error   react-reparenting@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/defoxe/.npm/_logs/2024-07-03T15_10_15_598Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/defoxe/.npm/_logs/2024-07-03T15_10_15_598Z-debug-0.log
```

### Task
- [ ] Fix dependencies to install package
- [ ] Make sure the other installed packages still exist and work

**Comment by ZachHunt359** [comment]
### Checked which specific peerDependencies it requires
PS D:\Dev\SpadeBoard\Spadeboard\frontend> npm info react-reparenting peerDependencies
{ react: '^16.8.5 || ^17.0.1' }

### Tried to allow the install by bypassing the peerDependencies (to see if React v18 would be compatible after all), and got several errors suggetsing Node.js needs updated
PS D:\Dev\SpadeBoard\Spadeboard\frontend> npm install react-reparenting --legacy-peer-deps
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@testing-library/react@16.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }        
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/eslint-plugin@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },        
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }        
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/parser@7.14.1',       
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },        
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }        
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/scope-manager@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },        
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }        
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/type-utils@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/typescript-estree@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/utils@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/visitor-keys@7.14.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'p-limit@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cssstyle@4.0.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'data-urls@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'execa@8.0.1',
npm WARN EBADENGINE   required: { node: '>=16.17' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'html-encoding-sniffer@4.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'human-signals@5.0.0',
npm WARN EBADENGINE   required: { node: '>=16.17.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jsdom@24.1.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@4.18.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tr46@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite@5.3.2',
npm WARN EBADENGINE   required: { node: '^18.0.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite-node@1.6.0',
npm WARN EBADENGINE   required: { node: '^18.0.0 || >=20.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vitest@1.6.0',
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'w3c-xmlserializer@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-encoding@3.1.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-mimetype@4.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-url@14.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'xml-name-validator@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated re-resizable-rotate@0.0.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated react-draggable-rotate@0.0.21: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 305 packages, and audited 306 packages in 24s

63 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

### From what I can find, to update Node.js in a Docker container means updating the first part of the Dockerfile, one or both of these two lines. Still investigating how exactly to alter them to get a more recent version of Node.js
# Use the official Node.js image as a base
FROM node:22-alpine

# Set environment variable
ENV NODE_ENV=development

**Comment by ZachHunt359** [comment]
### Updated the frontend Dockerfile to use node:latest
```
# Use the official Node.js image as a base
FROM node:latest

# Set environment variable
ENV NODE_ENV=development
```

### Rebuilt image
```
PS D:\Dev\SpadeBoard\Spadeboard\frontend> docker-compose up --build
[+] Building 20.4s (23/23) FINISHED                                                                                                                                                                        docker:desktop-linux
 => [backend internal] load build definition from Dockerfile                                                                                                                                                               0.0s
 => => transferring dockerfile: 1.15kB                                                                                                                                                                                     0.0s 
 => [backend internal] load metadata for docker.io/library/python:latest                                                                                                                                                   1.1s 
 => [backend auth] library/python:pull token for registry-1.docker.io                                                                                                                                                      0.0s
 => [backend internal] load .dockerignore                                                                                                                                                                                  0.0s
 => => transferring context: 375B                                                                                                                                                                                          0.0s 
 => [backend 1/6] FROM docker.io/library/python:latest@sha256:d12b529fba98bcc93e2e2e837c0a60efaa6328775965a43c1b8161cfbd8f10f3                                                                                             0.0s 
 => [backend internal] load build context                                                                                                                                                                                  0.0s 
 => => transferring context: 14.43kB                                                                                                                                                                                       0.0s 
 => CACHED [backend 2/6] COPY ./backend/requirements.txt /app/backend/requirements.txt                                                                                                                                     0.0s 
 => CACHED [backend 3/6] RUN python -m pip install -r /app/backend/requirements.txt                                                                                                                                        0.0s 
 => CACHED [backend 4/6] WORKDIR /app/backend                                                                                                                                                                              0.0s 
 => CACHED [backend 5/6] COPY ./backend /app/backend                                                                                                                                                                       0.0s 
 => CACHED [backend 6/6] RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app/backend                                                                                                       0.0s 
 => [backend] exporting to image                                                                                                                                                                                           0.0s 
 => => exporting layers                                                                                                                                                                                                    0.0s 
 => => writing image sha256:941bfe3815b995d0ff2b083f55347f79537db590a08271504fb4df6a31711bdc                                                                                                                               0.0s 
 => => naming to docker.io/library/spadeboard-backend                                                                                                                                                                      0.0s 
 => [frontend internal] load build definition from Dockerfile                                                                                                                                                              0.0s
 => => transferring dockerfile: 549B                                                                                                                                                                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:latest                                                                                                                                                    1.6s
 => [frontend auth] library/node:pull token for registry-1.docker.io                                                                                                                                                       0.0s
 => [frontend internal] load .dockerignore                                                                                                                                                                                 0.0s
 => => transferring context: 375B                                                                                                                                                                                          0.0s
 => [frontend 1/5] FROM docker.io/library/node:latest@sha256:2558f19e787cb0baed81a8068adf7509023b43dedce24ed606f8a01522b21313                                                                                              6.5s
 => => resolve docker.io/library/node:latest@sha256:2558f19e787cb0baed81a8068adf7509023b43dedce24ed606f8a01522b21313                                                                                                       0.0s 
 => => sha256:4d7bcfe46effa474ca1be502a1d97878bf972ac6507eda2cf93d57c09a9400d0 2.49kB / 2.49kB                                                                                                                             0.0s 
 => => sha256:a3146073457c8e12e3de3d59fe9e2d6eb06f8b1d7384b2cfe35ce78cc5940250 6.60kB / 6.60kB                                                                                                                             0.0s 
 => => sha256:b067ecbfab4fe7bba9616e90071d85967bb0d194f118145b4ffe28c5d0026ba9 1.25MB / 1.25MB                                                                                                                             1.0s 
 => => sha256:2558f19e787cb0baed81a8068adf7509023b43dedce24ed606f8a01522b21313 6.41kB / 6.41kB                                                                                                                             0.0s 
 => => sha256:d0078cb5df4578846ca6d1a44499337752057d68da49a7bd9da73d67782fe6b6 3.32kB / 3.32kB                                                                                                                             0.2s 
 => => sha256:11ee31c98c928249e90131c569fbeac09fae1ed4b5312d6a95ef33aaf0046fc0 53.03MB / 53.03MB                                                                                                                           3.6s 
 => => extracting sha256:d0078cb5df4578846ca6d1a44499337752057d68da49a7bd9da73d67782fe6b6                                                                                                                                  0.0s 
 => => sha256:65fcc43c3afb298ff7659802dc9db3e3ce36d8b609a69d531c7a3861e5b52a6e 448B / 448B                                                                                                                                 0.6s 
 => => extracting sha256:11ee31c98c928249e90131c569fbeac09fae1ed4b5312d6a95ef33aaf0046fc0                                                                                                                                  2.7s 
 => => extracting sha256:b067ecbfab4fe7bba9616e90071d85967bb0d194f118145b4ffe28c5d0026ba9                                                                                                                                  0.0s 
 => => extracting sha256:65fcc43c3afb298ff7659802dc9db3e3ce36d8b609a69d531c7a3861e5b52a6e                                                                                                                                  0.0s 
 => [frontend internal] load build context                                                                                                                                                                                 0.2s 
 => => transferring context: 311.58kB                                                                                                                                                                                      0.2s 
 => [frontend 2/5] WORKDIR /app/frontend                                                                                                                                                                                   0.7s 
 => [frontend 3/5] COPY ./frontend/package*.json ./                                                                                                                                                                        0.0s 
 => [frontend 4/5] RUN npm install                                                                                                                                                                                         8.0s 
 => [frontend 5/5] COPY ./frontend ./                                                                                                                                                                                      0.0s 
 => [frontend] exporting to image                                                                                                                                                                                          1.9s 
 => => exporting layers                                                                                                                                                                                                    1.9s 
 => => writing image sha256:e8be79b9f5a8cfc2bd5d766de6dd5988a525aafa4bb6a3800ac219a7cb5a69e6                                                                                                                               0.0s 
 => => naming to docker.io/library/spadeboard-frontend                                                                                                                                                                     0.0s 
[+] Running 4/4
 ✔ Container db        Created                                                                                                                                                                                             0.0s 
 ✔ Container pgadmin   Created                                                                                                                                                                                             0.0s 
 ✔ Container backend   Recreated                                                                                                                                                                                           0.2s 
 ✔ Container frontend  Recreated                                                                                                                                                                                           0.2s 
Attaching to backend, db, frontend, pgadmin
db        | 
db        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db        | 
db        | 2024-07-04 22:01:19.846 UTC [1] LOG:  starting PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
db        | 2024-07-04 22:01:19.846 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db        | 2024-07-04 22:01:19.846 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db        | 2024-07-04 22:01:19.850 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db        | 2024-07-04 22:01:19.860 UTC [29] LOG:  database system was shut down at 2024-07-04 21:50:06 UTC
db        | 2024-07-04 22:01:19.870 UTC [1] LOG:  database system is ready to accept connections
backend   | /app/backend/entrypoint.sh: line 2: $'\r': command not found
pgadmin   | postfix/postlog: starting the Postfix mail system
frontend  | 
frontend  | > frontend@0.0.0 dev
frontend  | > vite
frontend  | 
frontend  | 
frontend  |   VITE v5.3.2  ready in 178 ms
frontend  | 
frontend  |   ➜  Local:   http://localhost:3000/
frontend  |   ➜  Network: http://172.19.0.3:3000/
backend   | usage: manage.py makemigrations [-h] [--dry-run] [--merge] [--empty]
backend   |                                 [--noinput] [-n NAME] [--no-header] [--check]
backend   |                                 [--scriptable] [--update] [--version]
backend   |                                 [-v {0,1,2,3}] [--settings SETTINGS]
backend   |                                 [--pythonpath PYTHONPATH] [--traceback]
backend   |                                 [--no-color] [--force-color] [--skip-checks]
backend   |                                 [app_label ...]
backend   | manage.py makemigrations: error: unrecognized arguments: --noinput
backend   | usage: manage.py migrate [-h] [--noinput] [--database DATABASE] [--fake]
backend   |                          [--fake-initial] [--plan] [--run-syncdb] [--check]
backend   |                          [--prune] [--version] [-v {0,1,2,3}]
backend   |                          [--settings SETTINGS] [--pythonpath PYTHONPATH]
backend   |                          [--traceback] [--no-color] [--force-color]
backend   |                          [--skip-checks]
backend   |                          [app_label] [migration_name]
backend   | manage.py migrate: error: unrecognized arguments: --noinput
backend   | /app/backend/entrypoint.sh: line 6: $'\r': command not found
backend   | Watching for file changes with StatReloader
backend   | Performing system checks...
backend   | 
backend   | System check identified no issues (0 silenced).
backend   | Exception in thread django-main-thread:
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 187, in check_key
backend   |     return self.graph.root_nodes(key[0])[0]
backend   |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
backend   | IndexError: list index out of range
backend   | 
backend   | During handling of the above exception, another exception occurred:
backend   | 
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
backend   |     self.run()
backend   |   File "/usr/local/lib/python3.12/threading.py", line 1010, in run
backend   |     self._target(*self._args, **self._kwargs)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
backend   |     fn(*args, **kwargs)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 136, in inner_run
backend   |     self.check_migrations()
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 581, in check_migrations
backend   |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
backend   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
backend   |     self.loader = MigrationLoader(self.connection)
backend   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
backend   |     self.build_graph()
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 250, in build_graph
backend   |     self.add_external_dependencies(key, migration)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
backend   |     parent = self.check_key(parent, key[0])
backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 194, in check_key
backend   |     raise ValueError(
backend   | ValueError: Dependency on app with no migrations: authentication
pgadmin   | [2024-07-04 22:01:36 +0000] [1] [INFO] Starting gunicorn 22.0.0
pgadmin   | [2024-07-04 22:01:36 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin   | [2024-07-04 22:01:36 +0000] [1] [INFO] Using worker: gthread
pgadmin   | [2024-07-04 22:01:36 +0000] [83] [INFO] Booting worker with pid: 83
```

### Edited the line endings in entrypoint.sh to use LF instead of CLRF, and changed --noinput to --no-input.
### Because of 'ValueError: Dependency on app with no migrations: authentication', and at the suggestion of ChatGPT, I tried to make a migration (very likely where I messed up)
```
python manage.py makemigrations authentication
python manage.py migrate
```

### Tried to rebuild again
```
PS D:\Dev\SpadeBoard\Spadeboard> docker-compose up --build
[+] Building 2.9s (23/23) FINISHED                                                                                                                                                                         docker:desktop-linux 
 => [backend internal] load build definition from Dockerfile                                                                                                                                                               0.0s 
 => => transferring dockerfile: 1.15kB                                                                                                                                                                                     0.0s 
 => [backend internal] load metadata for docker.io/library/python:latest                                                                                                                                                   1.0s 
 => [backend auth] library/python:pull token for registry-1.docker.io                                                                                                                                                      0.0s 
 => [backend internal] load .dockerignore                                                                                                                                                                                  0.0s 
 => => transferring context: 375B                                                                                                                                                                                          0.0s 
 => [backend 1/6] FROM docker.io/library/python:latest@sha256:d12b529fba98bcc93e2e2e837c0a60efaa6328775965a43c1b8161cfbd8f10f3                                                                                             0.0s 
 => [backend internal] load build context                                                                                                                                                                                  0.0s 
 => => transferring context: 14.43kB                                                                                                                                                                                       0.0s 
 => CACHED [backend 2/6] COPY ./backend/requirements.txt /app/backend/requirements.txt                                                                                                                                     0.0s 
 => CACHED [backend 3/6] RUN python -m pip install -r /app/backend/requirements.txt                                                                                                                                        0.0s 
 => CACHED [backend 4/6] WORKDIR /app/backend                                                                                                                                                                              0.0s 
 => [backend 5/6] COPY ./backend /app/backend                                                                                                                                                                              0.1s 
 => [backend 6/6] RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app/backend                                                                                                              0.5s 
 => [backend] exporting to image                                                                                                                                                                                           0.0s
 => => exporting layers                                                                                                                                                                                                    0.0s
 => => writing image sha256:e5db8f8c0ad9cbd51cfc51a6577705a0c75cc5a33e4b1acaa11e928e56457067                                                                                                                               0.0s
 => => naming to docker.io/library/spadeboard-backend                                                                                                                                                                      0.0s 
 => [frontend internal] load build definition from Dockerfile                                                                                                                                                              0.0s
 => => transferring dockerfile: 549B                                                                                                                                                                                       0.0s 
 => [frontend internal] load metadata for docker.io/library/node:latest                                                                                                                                                    0.8s 
 => [frontend auth] library/node:pull token for registry-1.docker.io                                                                                                                                                       0.0s
 => [frontend internal] load .dockerignore                                                                                                                                                                                 0.0s
 => => transferring context: 375B                                                                                                                                                                                          0.0s 
 => [frontend 1/5] FROM docker.io/library/node:latest@sha256:2558f19e787cb0baed81a8068adf7509023b43dedce24ed606f8a01522b21313                                                                                              0.0s 
 => [frontend internal] load build context                                                                                                                                                                                 0.0s 
 => => transferring context: 311.58kB                                                                                                                                                                                      0.0s 
 => CACHED [frontend 2/5] WORKDIR /app/frontend                                                                                                                                                                            0.0s 
 => CACHED [frontend 3/5] COPY ./frontend/package*.json ./                                                                                                                                                                 0.0s 
 => CACHED [frontend 4/5] RUN npm install                                                                                                                                                                                  0.0s 
 => CACHED [frontend 5/5] COPY ./frontend ./                                                                                                                                                                               0.0s 
 => [frontend] exporting to image                                                                                                                                                                                          0.0s 
 => => exporting layers                                                                                                                                                                                                    0.0s 
 => => writing image sha256:e8be79b9f5a8cfc2bd5d766de6dd5988a525aafa4bb6a3800ac219a7cb5a69e6                                                                                                                               0.0s 
 => => naming to docker.io/library/spadeboard-frontend                                                                                                                                                                     0.0s 
[+] Running 4/4
 ✔ Container db        Running                                                                                                                                                                                             0.0s 
 ✔ Container backend   Recreated                                                                                                                                                                                          10.8s 
 ✔ Container pgadmin   Running                                                                                                                                                                                             0.0s 
 ✔ Container frontend  Recreated                                                                                                                                                                                           1.0s 
Attaching to backend, db, frontend, pgadmin
frontend  | 
frontend  | > frontend@0.0.0 dev
frontend  | > vite
frontend  | 
db        | 2024-07-04 22:16:40.180 UTC [27] LOG:  checkpoint starting: time
frontend  | 
frontend  |   VITE v5.3.2  ready in 176 ms
frontend  | 
frontend  |   ➜  Local:   http://localhost:3000/
frontend  |   ➜  Network: http://172.19.0.3:3000/
backend   | Migrations for 'authentication':
backend   |   authentication/migrations/0001_initial_migration.py
backend   |     - Create model User
backend   | Traceback (most recent call last):
backend   |   File "/app/backend/manage.py", line 22, in <module>
backend   |     main()
backend   |   File "/app/backend/manage.py", line 18, in main
backend   |     execute_from_command_line(sys.argv)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
backend   |     utility.execute()
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
backend   |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
backend   |     self.execute(*args, **cmd_options)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
backend   |     output = self.handle(*args, **options)
backend   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
backend   |     res = handle_func(*args, **kwargs)
backend   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend   |   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 120, in handle
backend   |     executor.loader.check_consistent_history(connection)
backend   |   File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history
backend   |     raise InconsistentMigrationHistory(
backend   | django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency authentication.0001_initial_migration on database 'default'.
backend   | Watching for file changes with StatReloader
backend   | Performing system checks...
backend   | 
backend   | System check identified no issues (0 silenced).
backend   | 
backend   | You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): authentication.
backend   | Run 'python manage.py migrate' to apply them.
backend   | July 04, 2024 - 22:16:43
backend   | Django version 5.0.6, using settings 'project.settings'
backend   | Starting development server at http://0.0.0.0:8000/
backend   | Quit the server with CONTROL-C.
backend   | 
db        | 2024-07-04 22:16:55.359 UTC [27] LOG:  checkpoint complete: wrote 154 buffers (0.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=15.144 s, sync=0.029 s, total=15.180 s; sync files=140, longest=0.004 s, average=0.001 s; distance=757 kB, estimate=757 kB; lsn=0/1A1BE18, redo lsn=0/1A19DE8
```

**Comment by jmai136** [comment]
Ended up installing `react-reverse-portal`.
